name: Deploy to Hetzner
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  
    steps:
      - name: Update remote repository
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          password: ${{ secrets.SSH_KEY }}
