name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: | 
          hugo --minify

      - name: Deploy
        uses: up9cloud/action-rsync@master
        env:
          SOURCE: ./public/
          ARGS_MORE: --checksum
          VERBOSE: true
          
          HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          # TODO: Change to key-based authentication
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
