name: Telegram bot pull request notify

on:
  pull_request:
    types: ["opened"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "Send message"
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Pull request opened in ${{ github.event.repository.name }}:
            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.name }}
            ${{ github.event.pull_request.body }}
            ${{ github.event.pull_request.url }}
